version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: postgresql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRED_DB=secretcli
    ports:
      - "5432:5432"