global:
  scrape_interval: 15s # How frequently Prometheus scrapes metrics

scrape_configs:
- job_name: 'secretcli-web' # Name of the job
  static_configs:
  - targets: ['localhost:8080'] # Scrape Go service at 'secretcli-web' container on port 8080
