{{ $app_name := env "APP_NAME" | default "secretcli-web"}}

repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: grafana
  url: https://grafana.github.io/helm-charts

releases:
- name: postgresql
  namespace: {{ $app_name }}
  chart: bitnami/postgresql
  version: "12.1.2"
  values:
  - values/postgres-db/values.yaml

- name: prometheus
  namespace: monitoring
  chart: prometheus-community/prometheus
  version: 25.16.0
  values:
  - values/prometheus/values.yaml

- name: grafana
  namespace: monitoring
  chart: grafana/grafana
  version: 7.3.6
  values:
  - values/grafana/values.yaml