apiVersion: v1
kind: Service
metadata:
  name: {{ template "secretcli-web.name" . }}-svc
    {{- include "secretcli-web.labels" . | nindent 2 }}
    app: {{ template "secretcli-web.name" . }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: secretcli-web-server
  selector:
    name: {{ template "secretcli-web.name" . }}
    component: app
    release: {{ .Release.Name }}
