serverFiles:
  alerting_rules.yml:
    groups:
    - name: secretcli-web
      rules:
      - alert: SecretcliWebUp
        expr: up{job="secretcli-web"} == 1
        labels:
          severity: info
        annotations:
          summary: "Secretcli web is up"
          description: "Secretcli web is up"

    - name: secretcli-postgres-db
      rules:
      - alert: SecretcliPostgresqlDatabaseUp
        expr: up{job="secretcli-postgres-db"} == 1
        labels:
          severity: info
        annotations:
          summary: "Secretcli postgresql database is up"
          description: "Secretcli postgresql database is up"

extraScrapeConfigs: |
  - job_name: secretcli-web
    static_configs:
      - targets:
          - secretcli-web-svc.secretcli-web.svc.cluster.local:80
  - job_name: secretcli-postgres-db
    static_configs:
      - targets:
          - postgresql-metrics.secretcli-web.svc.cluster.local:9187

alertmanager:
  enabled: true
